# Development configuration
vector_db:
  provider: "qdrant"
  url: "http://localhost:6333"  # Local Qdrant instance
  api_key: ""  # No API key needed for local
  collection: "TestCollection6"
  timeout: 30

embedding:
  provider: "ollama"
  model: "bge-m3"
  base_url: "http://localhost:11434"
  api_key: ""
  dimensions: 1024

api:
  host: "0.0.0.0"
  port: 8001
  reload: true  # Auto-reload for development
  log_level: "DEBUG"
  cors_origins:
    - "*"

environment: "development"
